# Generated by Django 4.2.7 on 2023-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_time_block', '0002_alter_timeblock_object_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['object_id', 'end_datetime'], name='django_time_object__7ce4e8_idx'),
        ),
    ]
