# Generated by Django 4.0.6 on 2023-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_time_block', '0003_timeblock_django_time_object__7ce4e8_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
