# Generated by Django 4.0.6 on 2023-12-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_time_block', '0004_relationtimeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtimeblock',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
